apiVersion: extensions/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: nats-publisher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nats-publisher
        version: v.0.0.1
    spec:
      containers:
      - name: nats-publisher
        image: docker.io/jsenon/nats-publisher:latest
        imagePullPolicy: Always